name: deploy project

on:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - name: Get SSH Keys and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      - name: Deploy using SCP
        run: scp -o StrictHostKey
        
